### ISSUE TITLE
Update to latest hermes dependency

### ISSUE THREAD

**Issue by djbeaumont** [wardle/hades#4]
I'm foolishly using the latest commits of both hermes and hades and have run into a problem where it looks like lucene was upgraded in hermes but the version of hermes depended on by hades hasn't been updated.

That results in:
```
Exception in thread "main" org.apache.lucene.index.IndexFormatTooNewException: Format version is not supported (resource MMapIndexInput(path="/usr/local/bin/snomed.db/search.db/_14o.fdt")): 4 (needs to be between 1 and 3)
	at org.apache.lucene.codecs.CodecUtil.checkHeaderNoMagic(CodecUtil.java:216)
	at org.apache.lucene.codecs.CodecUtil.checkHeader(CodecUtil.java:198)
	at org.apache.lucene.codecs.CodecUtil.checkIndexHeader(CodecUtil.java:255)
	at org.apache.lucene.codecs.compressing.CompressingStoredFieldsReader.<init>(CompressingStoredFieldsReader.java:130)
	at org.apache.lucene.codecs.compressing.CompressingStoredFieldsFormat.fieldsReader(CompressingStoredFieldsFormat.java:123)
	at org.apache.lucene.codecs.lucene87.Lucene87StoredFieldsFormat.fieldsReader(Lucene87StoredFieldsFormat.java:131)
	at org.apache.lucene.index.SegmentCoreReaders.<init>(SegmentCoreReaders.java:127)
	at org.apache.lucene.index.SegmentReader.<init>(SegmentReader.java:83)
	at org.apache.lucene.index.StandardDirectoryReader$1.doBody(StandardDirectoryReader.java:66)
	at org.apache.lucene.index.StandardDirectoryReader$1.doBody(StandardDirectoryReader.java:58)
	at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:720)
	at org.apache.lucene.index.StandardDirectoryReader.open(StandardDirectoryReader.java:81)
	at org.apache.lucene.index.DirectoryReader.open(DirectoryReader.java:63)
	at com.eldrix.hermes.impl.search$open_index_reader.invokeStatic(search.clj:129)
	at com.eldrix.hermes.impl.search$open_index_reader.invoke(search.clj:126)
	at com.eldrix.hermes.core$open.invokeStatic(core.clj:249)
	at com.eldrix.hermes.core$open.invoke(core.clj:244)
	at com.eldrix.hades.core$_main.invokeStatic(core.clj:191)
	at com.eldrix.hades.core$_main.doInvoke(core.clj:185)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at com.eldrix.hades.core.main(Unknown Source)
```

**Comment by wardle** [comment]
Try 536c9ff46d7a702c89d5b25ec7d09059916cbb18

**Comment by wardle** [comment]
I didn't think anyone else would be using head, other than me. I don't plan on keeping hades in sync with every commit, but would for every release. The easy fix is to just use the commit before that, or a tagged release. But the deps are easy to upgrade too - see deps.edn - I just use a git coordinate with the SHA of the commit.

**Comment by djbeaumont** [comment]
I have now added a specific commit to my build scripts for both hades and hermes after bumping into this, but I thought it was worth mentioning :)

**Comment by wardle** [comment]
Sorry I copied the wrong commit hash above - now corrected to 536c9ff46d7a702c89d5b25ec7d09059916cbb18

Should work, and my tests show backwards compatible.

**Comment by wardle** [comment]
Thanks David - no it is brilliant to have feedback. Did you see my comments re Spanish distribution in Hermes - I am tempted to add a "--keep-going" flag for import in case of errors but I'm still undecided.

**Comment by djbeaumont** [comment]
Just testing now, hence running into this issue when my simplistic `git checkout ...hermes` Dockerfile ran into problems. I'll let you know on the other thread. Thanks again for all your help!
